# © 2026 Martín Viera. Todos los derechos reservados.
"""Catálogo de preguntas del relevamiento, una por una, separadas por etapa del
pipeline. Cada pregunta trae el «por qué se pregunta»: qué decisión del pipeline
depende de esa respuesta. Sin eso es un cuestionario; con eso es una entrevista.

Los textos se mezclan en ``i18n._T`` (igual que los de la bitácora), así el test
de paridad ES/EN/PT también los cubre.

`PREGUNTAS` es el orden en que se hacen: (etapa, id, rol al que corresponde).
"""
from __future__ import annotations

# Rol típico que sabe la respuesta. No es quién la contesta al final (eso se
# anota en la respuesta), es a quién conviene ir a buscar.
ROLES = ("ti", "datos", "negocio", "seguridad", "operaciones")

PREGUNTAS: list[tuple[str, str, str]] = [
    # 1 · fuentes
    ("fuentes", "sistemas", "ti"),
    ("fuentes", "acceso", "ti"),
    ("fuentes", "volumen", "ti"),
    ("fuentes", "historia", "negocio"),
    ("fuentes", "dueno_origen", "ti"),
    # 2 · bronze
    ("bronze", "entrega", "ti"),
    ("bronze", "reproceso", "datos"),
    ("bronze", "retencion", "seguridad"),
    # 3 · silver
    ("silver", "glosario", "negocio"),
    ("silver", "codigos", "datos"),
    ("silver", "exclusiones", "negocio"),
    ("silver", "duplicados", "datos"),
    ("silver", "calculos", "negocio"),
    # 4 · calidad
    ("calidad", "criticas", "negocio"),
    ("calidad", "rangos", "negocio"),
    ("calidad", "obligatorios", "datos"),
    ("calidad", "conciliacion", "negocio"),
    ("calidad", "aviso", "operaciones"),
    # 5 · gold
    ("gold", "granularidad", "negocio"),
    ("gold", "jerarquias", "negocio"),
    ("gold", "historia_cambios", "negocio"),
    ("gold", "calendario", "negocio"),
    # 6 · almacén
    ("almacen", "destino", "ti"),
    ("almacen", "ventana", "operaciones"),
    ("almacen", "concurrencia", "ti"),
    # 7 · gobernanza
    ("gobernanza", "dueno_dato", "negocio"),
    ("gobernanza", "pii", "seguridad"),
    ("gobernanza", "accesos", "seguridad"),
    ("gobernanza", "normativa", "seguridad"),
    ("gobernanza", "retencion_legal", "seguridad"),
    # 8 · ML
    ("ml", "decision", "negocio"),
    ("ml", "objetivo", "datos"),
    ("ml", "casos", "datos"),
    ("ml", "accion", "operaciones"),
    # 9 · reporte
    ("reporte", "kpis", "negocio"),
    ("reporte", "formulas", "negocio"),
    ("reporte", "audiencia", "negocio"),
    ("reporte", "cortes", "negocio"),
    ("reporte", "hoy", "operaciones"),
    # 10 · DAX
    ("dax", "medidas", "datos"),
    ("dax", "comparaciones", "negocio"),
    # 11 · Power BI
    ("powerbi", "herramienta", "ti"),
    ("powerbi", "publicacion", "ti"),
    ("powerbi", "refresco", "operaciones"),
    # 12 · entrega
    ("entrega", "frecuencia", "operaciones"),
    ("entrega", "responsable", "operaciones"),
    ("entrega", "falla", "operaciones"),
    ("entrega", "exito", "negocio"),
]

TEXTOS: dict[str, dict[str, str]] = {
    # ------------------------------------------------------------- roles
    "rol_ti": {"es": "TI / Sistemas", "en": "IT / Systems", "pt": "TI / Sistemas"},
    "rol_datos": {"es": "Datos / BI", "en": "Data / BI", "pt": "Dados / BI"},
    "rol_negocio": {"es": "Negocio / Área usuaria", "en": "Business / User area", "pt": "Negócio / Área usuária"},
    "rol_seguridad": {"es": "Seguridad / Legal", "en": "Security / Legal", "pt": "Segurança / Jurídico"},
    "rol_operaciones": {"es": "Operaciones", "en": "Operations", "pt": "Operações"},

    # ------------------------------------------------------------- 1 · fuentes
    "rq_fuentes_sistemas": {"es": "¿De qué sistemas sale la información que necesitamos? (ERP, CRM, planillas, archivos, APIs)",
                            "en": "Which systems does the information we need come from? (ERP, CRM, spreadsheets, files, APIs)",
                            "pt": "De quais sistemas sai a informação de que precisamos? (ERP, CRM, planilhas, arquivos, APIs)"},
    "rq_fuentes_sistemas_por": {"es": "Define la lista de fuentes del YAML. Una fuente que aparece a mitad del proyecto obliga a rehacer el modelo.",
                                "en": "Defines the source list in the YAML. A source that shows up mid-project forces the model to be redone.",
                                "pt": "Define a lista de fontes no YAML. Uma fonte que aparece no meio do projeto obriga a refazer o modelo."},
    "rq_fuentes_acceso": {"es": "¿Cómo accedemos a cada uno: usuario de base de sólo lectura, exportación programada, API, archivo en carpeta?",
                          "en": "How do we access each one: read-only database user, scheduled export, API, file in a folder?",
                          "pt": "Como acessamos cada um: usuário de banco somente leitura, exportação agendada, API, arquivo em pasta?"},
    "rq_fuentes_acceso_por": {"es": "Decide el tipo de fuente y si hace falta pedir una cuenta de servicio. Es el trámite que más demora el arranque.",
                              "en": "Decides the source type and whether a service account must be requested. It is the paperwork that most delays the start.",
                              "pt": "Decide o tipo de fonte e se é preciso pedir uma conta de serviço. É o trâmite que mais atrasa o começo."},
    "rq_fuentes_volumen": {"es": "¿Cuántos registros tiene hoy cada origen y cuánto crece por mes?",
                           "en": "How many records does each source hold today, and how much does it grow per month?",
                           "pt": "Quantos registros cada origem tem hoje e quanto cresce por mês?"},
    "rq_fuentes_volumen_por": {"es": "Define si alcanza con leer todo cada vez o hay que cargar incremental, y el tamaño de la máquina.",
                               "en": "Decides whether reading everything each time is enough or an incremental load is needed, and the machine size.",
                               "pt": "Define se basta ler tudo toda vez ou é preciso carga incremental, e o tamanho da máquina."},
    "rq_fuentes_historia": {"es": "¿Desde qué fecha hay historia disponible, y desde cuándo la necesitamos para el análisis?",
                            "en": "From what date is history available, and from when do we need it for the analysis?",
                            "pt": "Desde que data há histórico disponível, e a partir de quando precisamos dele para a análise?"},
    "rq_fuentes_historia_por": {"es": "Sin dos años de historia no hay estacionalidad, y sin estacionalidad no hay proyección que valga.",
                                "en": "Without two years of history there is no seasonality, and without seasonality no forecast is worth much.",
                                "pt": "Sem dois anos de histórico não há sazonalidade, e sem sazonalidade não há projeção que valha."},
    "rq_fuentes_dueno_origen": {"es": "¿Quién es el dueño de cada sistema origen y a quién se le pide un cambio o un permiso?",
                                "en": "Who owns each source system, and who do we ask for a change or a permission?",
                                "pt": "Quem é o dono de cada sistema de origem e a quem se pede uma mudança ou permissão?"},
    "rq_fuentes_dueno_origen_por": {"es": "El día que el origen cambie una columna sin avisar, esa persona es la que destraba el problema.",
                                    "en": "The day the source changes a column without warning, that person is who unblocks it.",
                                    "pt": "No dia em que a origem mudar uma coluna sem avisar, essa pessoa é quem destrava o problema."},

    # ------------------------------------------------------------- 2 · bronze
    "rq_bronze_entrega": {"es": "Si vienen archivos, ¿cómo llegan (carpeta de red, SFTP, mail), con qué nombre y en qué formato exacto?",
                          "en": "If files arrive, how do they arrive (network folder, SFTP, email), with what name and in exactly what format?",
                          "pt": "Se vêm arquivos, como chegam (pasta de rede, SFTP, e-mail), com que nome e em que formato exato?"},
    "rq_bronze_entrega_por": {"es": "El separador, la codificación y el nombre del archivo son la mitad de los errores de ingesta del primer mes.",
                              "en": "The delimiter, the encoding and the file name are half of the first month's ingestion errors.",
                              "pt": "O separador, a codificação e o nome do arquivo são metade dos erros de ingestão do primeiro mês."},
    "rq_bronze_reproceso": {"es": "¿Puede llegar el mismo período dos veces, o corregido? ¿Qué hacemos con lo que ya habíamos cargado?",
                            "en": "Can the same period arrive twice, or corrected? What do we do with what was already loaded?",
                            "pt": "O mesmo período pode chegar duas vezes, ou corrigido? O que fazemos com o que já foi carregado?"},
    "rq_bronze_reproceso_por": {"es": "Define si la carga pisa o acumula. Equivocarse acá duplica los montos y nadie se da cuenta hasta el cierre.",
                                "en": "Decides whether the load overwrites or appends. Getting it wrong doubles the amounts and nobody notices until closing.",
                                "pt": "Define se a carga sobrescreve ou acumula. Errar aqui duplica os valores e ninguém percebe até o fechamento."},
    "rq_bronze_retencion": {"es": "¿Cuánto tiempo hay que guardar el dato crudo tal como llegó?",
                            "en": "How long must the raw data be kept exactly as it arrived?",
                            "pt": "Por quanto tempo é preciso guardar o dado bruto tal como chegou?"},
    "rq_bronze_retencion_por": {"es": "Es lo que permite auditar un número viejo y reprocesar sin volver a pedirle nada al origen.",
                                "en": "It is what allows auditing an old number and reprocessing without asking the source again.",
                                "pt": "É o que permite auditar um número antigo e reprocessar sem pedir nada à origem de novo."},

    # ------------------------------------------------------------- 3 · silver
    "rq_silver_glosario": {"es": "¿Qué significa exactamente cada campo clave, y quién define la definición oficial?",
                           "en": "What exactly does each key field mean, and who owns the official definition?",
                           "pt": "O que significa exatamente cada campo-chave, e quem define a definição oficial?"},
    "rq_silver_glosario_por": {"es": "Dos áreas que llaman «cliente» a cosas distintas producen dos reportes que nunca van a cerrar.",
                               "en": "Two areas calling different things “customer” produce two reports that will never reconcile.",
                               "pt": "Duas áreas que chamam de «cliente» coisas diferentes produzem dois relatórios que nunca vão bater."},
    "rq_silver_codigos": {"es": "¿Hay códigos que haya que traducir a etiquetas (1 = Activo, 2 = Baja)? ¿Dónde vive esa tabla de equivalencias?",
                          "en": "Are there codes to translate into labels (1 = Active, 2 = Closed)? Where does that lookup table live?",
                          "pt": "Há códigos que precisam virar rótulos (1 = Ativo, 2 = Baixa)? Onde vive essa tabela de equivalências?"},
    "rq_silver_codigos_por": {"es": "Va directo a `decodificar` del YAML. Sin eso el tablero muestra números que nadie sabe leer.",
                              "en": "Goes straight into the YAML's `decodificar`. Without it the dashboard shows numbers nobody can read.",
                              "pt": "Vai direto para `decodificar` do YAML. Sem isso o painel mostra números que ninguém sabe ler."},
    "rq_silver_exclusiones": {"es": "¿Qué registros NO deben contarse nunca: anulados, pruebas, internos, una sucursal que no cuenta?",
                              "en": "Which records must never be counted: voided, tests, internal, a branch that does not count?",
                              "pt": "Quais registros NUNCA devem ser contados: anulados, testes, internos, uma filial que não conta?"},
    "rq_silver_exclusiones_por": {"es": "Es el filtro del YAML y la causa número uno de que un total no coincida con el sistema origen.",
                                  "en": "It is the YAML filter and the number-one cause of a total not matching the source system.",
                                  "pt": "É o filtro do YAML e a causa número um de um total não bater com o sistema de origem."},
    "rq_silver_duplicados": {"es": "¿Puede haber filas repetidas legítimas? Si aparecen dos, ¿cuál es la buena?",
                             "en": "Can there be legitimate repeated rows? If two show up, which one is the good one?",
                             "pt": "Pode haver linhas repetidas legítimas? Se aparecerem duas, qual é a boa?"},
    "rq_silver_duplicados_por": {"es": "Define la clave de deduplicación. Sin regla clara se cuenta dos veces al mismo cliente.",
                                 "en": "Defines the dedup key. With no clear rule the same customer gets counted twice.",
                                 "pt": "Define a chave de deduplicação. Sem regra clara, conta-se o mesmo cliente duas vezes."},
    "rq_silver_calculos": {"es": "¿Qué cálculos ya existen hoy en planillas y hay que replicar exactamente igual?",
                           "en": "Which calculations already exist in spreadsheets today and must be replicated exactly?",
                           "pt": "Quais cálculos já existem hoje em planilhas e precisam ser replicados exatamente?"},
    "rq_silver_calculos_por": {"es": "Si el número nuevo no da igual que la planilla de siempre, el proyecto pierde credibilidad el primer día.",
                               "en": "If the new number differs from the usual spreadsheet, the project loses credibility on day one.",
                               "pt": "Se o número novo não bater com a planilha de sempre, o projeto perde credibilidade no primeiro dia."},

    # ------------------------------------------------------------- 4 · calidad
    "rq_calidad_criticas": {"es": "¿Qué error en el dato obligaría a NO publicar el reporte de ese día?",
                            "en": "What error in the data would force NOT publishing that day's report?",
                            "pt": "Que erro no dado obrigaria a NÃO publicar o relatório daquele dia?"},
    "rq_calidad_criticas_por": {"es": "Son las reglas críticas: las que cortan el pipeline. Publicar mal es peor que no publicar.",
                                "en": "These are the critical rules, the ones that stop the pipeline. Publishing wrong is worse than not publishing.",
                                "pt": "São as regras críticas: as que cortam o pipeline. Publicar errado é pior do que não publicar."},
    "rq_calidad_rangos": {"es": "¿Qué valores son imposibles en los campos clave? (una edad de 200, un monto negativo, una fecha futura)",
                          "en": "Which values are impossible in the key fields? (an age of 200, a negative amount, a future date)",
                          "pt": "Quais valores são impossíveis nos campos-chave? (uma idade de 200, um valor negativo, uma data futura)"},
    "rq_calidad_rangos_por": {"es": "Cada respuesta es una regla de rango que atrapa el error antes de que llegue al tablero.",
                              "en": "Each answer becomes a range rule that catches the error before it reaches the dashboard.",
                              "pt": "Cada resposta vira uma regra de faixa que pega o erro antes de chegar ao painel."},
    "rq_calidad_obligatorios": {"es": "¿Qué campos no pueden venir vacíos nunca?",
                                "en": "Which fields can never come in empty?",
                                "pt": "Quais campos nunca podem vir vazios?"},
    "rq_calidad_obligatorios_por": {"es": "Un campo clave vacío no se nota en el total pero rompe todos los cortes por esa dimensión.",
                                    "en": "An empty key field does not show in the total but breaks every breakdown by that dimension.",
                                    "pt": "Um campo-chave vazio não aparece no total mas quebra todos os cortes por essa dimensão."},
    "rq_calidad_conciliacion": {"es": "¿Contra qué número oficial se compara para saber que la carga salió bien?",
                                "en": "Against which official number do we compare to know the load went well?",
                                "pt": "Contra qual número oficial se compara para saber que a carga deu certo?"},
    "rq_calidad_conciliacion_por": {"es": "Sin un número contra el cual cerrar, «está bien» es una opinión. Con él, es una verificación.",
                                    "en": "With no number to reconcile against, “it is fine” is an opinion. With one, it is a check.",
                                    "pt": "Sem um número contra o qual fechar, «está certo» é opinião. Com ele, é verificação."},
    "rq_calidad_aviso": {"es": "Cuando algo falla, ¿a quién se le avisa, por qué canal y en cuánto tiempo?",
                         "en": "When something fails, who gets told, through what channel, and how fast?",
                         "pt": "Quando algo falha, quem é avisado, por qual canal e em quanto tempo?"},
    "rq_calidad_aviso_por": {"es": "Un pipeline que falla en silencio es peor que no tener pipeline: nadie sabe que el dato está mal.",
                             "en": "A pipeline that fails silently is worse than no pipeline: nobody knows the data is wrong.",
                             "pt": "Um pipeline que falha em silêncio é pior que não ter pipeline: ninguém sabe que o dado está errado."},

    # ------------------------------------------------------------- 5 · gold
    "rq_gold_granularidad": {"es": "¿A qué nivel de detalle se analiza: por cliente, por producto, por sucursal, por día?",
                             "en": "At what level of detail is it analysed: by customer, product, branch, day?",
                             "pt": "Em que nível de detalhe se analisa: por cliente, produto, filial, dia?"},
    "rq_gold_granularidad_por": {"es": "Es la granularidad de la tabla de hechos. Agregarla de más se puede; recuperar detalle que no se guardó, no.",
                                 "en": "It is the fact table's grain. Aggregating further is easy; recovering detail that was never stored is not.",
                                 "pt": "É a granularidade da tabela de fatos. Agregar mais dá; recuperar detalhe que não foi guardado, não."},
    "rq_gold_jerarquias": {"es": "¿Qué jerarquías existen? (producto → familia → categoría; vendedor → sucursal → región)",
                           "en": "Which hierarchies exist? (product → family → category; rep → branch → region)",
                           "pt": "Quais hierarquias existem? (produto → família → categoria; vendedor → filial → região)"},
    "rq_gold_jerarquias_por": {"es": "Son las dimensiones del modelo y los caminos de drill-down del tablero.",
                               "en": "They are the model's dimensions and the dashboard's drill-down paths.",
                               "pt": "São as dimensões do modelo e os caminhos de drill-down do painel."},
    "rq_gold_historia_cambios": {"es": "Cuando un cliente cambia de sucursal o un producto de categoría, ¿el histórico se reescribe o se conserva como estaba?",
                                 "en": "When a customer changes branch or a product changes category, is history rewritten or kept as it was?",
                                 "pt": "Quando um cliente muda de filial ou um produto de categoria, o histórico é reescrito ou mantido como estava?"},
    "rq_gold_historia_cambios_por": {"es": "Es la diferencia entre SCD 1 y SCD 2. Decide si el reporte de marzo va a seguir diciendo lo mismo dentro de un año.",
                                     "en": "It is the difference between SCD 1 and SCD 2. It decides whether March's report still says the same a year from now.",
                                     "pt": "É a diferença entre SCD 1 e SCD 2. Decide se o relatório de março vai continuar dizendo o mesmo daqui a um ano."},
    "rq_gold_calendario": {"es": "¿El año fiscal coincide con el calendario? ¿Hay semanas, campañas o períodos especiales?",
                           "en": "Does the fiscal year match the calendar? Are there special weeks, campaigns or periods?",
                           "pt": "O ano fiscal coincide com o calendário? Há semanas, campanhas ou períodos especiais?"},
    "rq_gold_calendario_por": {"es": "Define la tabla de calendario, de la que dependen todas las comparaciones contra el mes o el año anterior.",
                               "en": "Defines the calendar table, which every month-over-month and year-over-year comparison depends on.",
                               "pt": "Define a tabela de calendário, da qual dependem todas as comparações contra o mês ou o ano anterior."},

    # ------------------------------------------------------------- 6 · almacén
    "rq_almacen_destino": {"es": "¿Dónde tiene que quedar el resultado: base corporativa, archivos en una carpeta, lago de datos?",
                           "en": "Where must the result land: corporate database, files in a folder, data lake?",
                           "pt": "Onde o resultado precisa ficar: banco corporativo, arquivos em uma pasta, data lake?"},
    "rq_almacen_destino_por": {"es": "Define la publicación y quién más va a poder consumir el modelo sin pasar por nosotros.",
                               "en": "Defines publishing and who else can consume the model without going through us.",
                               "pt": "Define a publicação e quem mais vai poder consumir o modelo sem passar por nós."},
    "rq_almacen_ventana": {"es": "¿En qué franja horaria se puede procesar sin molestar a los sistemas que usa la gente?",
                           "en": "In what time window can we process without disturbing the systems people use?",
                           "pt": "Em que faixa horária dá para processar sem atrapalhar os sistemas que as pessoas usam?"},
    "rq_almacen_ventana_por": {"es": "Es el horario de la automatización, y evita la conversación incómoda de haber trabado el ERP un martes a las 10.",
                               "en": "It is the automation schedule, and avoids the awkward talk about having locked the ERP on a Tuesday at 10.",
                               "pt": "É o horário da automação, e evita a conversa constrangedora de ter travado o ERP numa terça às 10."},
    "rq_almacen_concurrencia": {"es": "¿Quién más escribe en ese destino? ¿Puede haber otro proceso tocando las mismas tablas?",
                                "en": "Who else writes to that destination? Could another process be touching the same tables?",
                                "pt": "Quem mais escreve nesse destino? Pode haver outro processo mexendo nas mesmas tabelas?"},
    "rq_almacen_concurrencia_por": {"es": "Dos procesos escribiendo la misma tabla producen números que cambian solos entre dos refrescos.",
                                    "en": "Two processes writing the same table produce numbers that change on their own between refreshes.",
                                    "pt": "Dois processos escrevendo na mesma tabela produzem números que mudam sozinhos entre dois refreshes."},

    # ------------------------------------------------------------- 7 · gobernanza
    "rq_gobernanza_dueno_dato": {"es": "¿Quién es el dueño del dato y quién aprueba un cambio de definición de un KPI?",
                                 "en": "Who owns the data, and who approves a change to a KPI's definition?",
                                 "pt": "Quem é o dono do dado e quem aprova uma mudança de definição de um KPI?"},
    "rq_gobernanza_dueno_dato_por": {"es": "Toda auditoría empieza por «¿de quién es este dato?». Sin dueño, cada cambio es una discusión nueva.",
                                     "en": "Every audit starts with “whose data is this?”. With no owner, each change is a fresh argument.",
                                     "pt": "Toda auditoria começa com «de quem é este dado?». Sem dono, cada mudança é uma discussão nova."},
    "rq_gobernanza_pii": {"es": "¿Qué campos son datos personales (documento, teléfono, mail, dirección, salario) y quién puede verlos?",
                          "en": "Which fields are personal data (ID, phone, email, address, salary) and who may see them?",
                          "pt": "Quais campos são dados pessoais (documento, telefone, e-mail, endereço, salário) e quem pode vê-los?"},
    "rq_gobernanza_pii_por": {"es": "Determina qué se enmascara antes de publicar y qué no puede salir del perímetro del cliente.",
                              "en": "Determines what gets masked before publishing and what must not leave the client's perimeter.",
                              "pt": "Determina o que é mascarado antes de publicar e o que não pode sair do perímetro do cliente."},
    "rq_gobernanza_accesos": {"es": "¿Quién puede ver qué? ¿Hay información restringida por área, sucursal o jerarquía?",
                              "en": "Who can see what? Is information restricted by area, branch or seniority?",
                              "pt": "Quem pode ver o quê? Há informação restrita por área, filial ou hierarquia?"},
    "rq_gobernanza_accesos_por": {"es": "Define la seguridad a nivel de fila del tablero. Agregarla después obliga a rehacer el modelo.",
                                  "en": "Defines the dashboard's row-level security. Adding it later forces the model to be redone.",
                                  "pt": "Define a segurança em nível de linha do painel. Adicionar depois obriga a refazer o modelo."},
    "rq_gobernanza_normativa": {"es": "¿Qué normativa aplica: protección de datos personales, auditoría interna, un regulador del sector?",
                                "en": "What regulation applies: personal data protection, internal audit, a sector regulator?",
                                "pt": "Que normativa se aplica: proteção de dados pessoais, auditoria interna, um regulador do setor?"},
    "rq_gobernanza_normativa_por": {"es": "Cambia qué se puede guardar, por cuánto tiempo y qué hay que poder demostrar si vienen a preguntar.",
                                    "en": "Changes what can be stored, for how long, and what must be provable if someone comes asking.",
                                    "pt": "Muda o que se pode guardar, por quanto tempo e o que é preciso poder provar se vierem perguntar."},
    "rq_gobernanza_retencion_legal": {"es": "¿Cuánto tiempo hay obligación de conservar la información, y cuándo hay obligación de borrarla?",
                                      "en": "How long must the information be kept, and when must it be deleted?",
                                      "pt": "Por quanto tempo há obrigação de conservar a informação, e quando há obrigação de apagá-la?"},
    "rq_gobernanza_retencion_legal_por": {"es": "Guardar de más también es un incumplimiento, no sólo guardar de menos.",
                                          "en": "Keeping too much is also a breach, not only keeping too little.",
                                          "pt": "Guardar demais também é um descumprimento, não só guardar de menos."},

    # ------------------------------------------------------------- 8 · ML
    "rq_ml_decision": {"es": "¿Qué decisión concreta se va a tomar distinto gracias a la predicción?",
                       "en": "What concrete decision will be made differently thanks to the prediction?",
                       "pt": "Que decisão concreta será tomada de forma diferente graças à previsão?"},
    "rq_ml_decision_por": {"es": "Si ninguna decisión cambia, el modelo es un adorno caro. Esta pregunta decide si vale la pena hacerlo.",
                           "en": "If no decision changes, the model is expensive decoration. This question decides whether it is worth building.",
                           "pt": "Se nenhuma decisão muda, o modelo é enfeite caro. Esta pergunta decide se vale a pena fazê-lo."},
    "rq_ml_objetivo": {"es": "¿Qué queremos predecir exactamente, y en qué momento se conoce la respuesta verdadera?",
                       "en": "What exactly do we want to predict, and when is the true answer known?",
                       "pt": "O que queremos prever exatamente, e em que momento se conhece a resposta verdadeira?"},
    "rq_ml_objetivo_por": {"es": "Define el target y la ventana. Usar información que en la vida real todavía no existe infla el modelo y lo hace fallar en producción.",
                           "en": "Defines the target and the window. Using information that does not yet exist in real life inflates the model and makes it fail in production.",
                           "pt": "Define o alvo e a janela. Usar informação que na vida real ainda não existe infla o modelo e o faz falhar em produção."},
    "rq_ml_casos": {"es": "¿Tenemos casos históricos con el resultado ya conocido? ¿Cuántos, y de qué período?",
                    "en": "Do we have historical cases with the outcome already known? How many, and from what period?",
                    "pt": "Temos casos históricos com o resultado já conhecido? Quantos, e de que período?"},
    "rq_ml_casos_por": {"es": "Sin casos etiquetados no hay modelo supervisado. Con pocos, hay un número que parece bueno y no se sostiene.",
                        "en": "With no labelled cases there is no supervised model. With few, there is a number that looks good and does not hold.",
                        "pt": "Sem casos rotulados não há modelo supervisionado. Com poucos, há um número que parece bom e não se sustenta."},
    "rq_ml_accion": {"es": "Según el resultado del modelo, ¿qué se hace distinto y quién ejecuta esa acción?",
                     "en": "Depending on the model's output, what is done differently and who executes that action?",
                     "pt": "Conforme o resultado do modelo, o que se faz diferente e quem executa essa ação?"},
    "rq_ml_accion_por": {"es": "Define los umbrales y la salida operativa: sin alguien que actúe, la predicción no cambia ningún resultado.",
                         "en": "Defines the thresholds and the operational output: with nobody acting on it, the prediction changes no outcome.",
                         "pt": "Define os limiares e a saída operacional: sem alguém que aja, a previsão não muda nenhum resultado."},

    # ------------------------------------------------------------- 9 · reporte
    "rq_reporte_kpis": {"es": "¿Cuáles son los cinco números que se miran todos los días?",
                        "en": "Which are the five numbers looked at every day?",
                        "pt": "Quais são os cinco números olhados todos os dias?"},
    "rq_reporte_kpis_por": {"es": "Son los KPIs del YAML y las medidas DAX. Cinco que se usan valen más que cuarenta que decoran.",
                            "en": "They are the YAML's KPIs and the DAX measures. Five that get used beat forty that decorate.",
                            "pt": "São os KPIs do YAML e as medidas DAX. Cinco que se usam valem mais que quarenta que enfeitam."},
    "rq_reporte_formulas": {"es": "Para cada uno de esos números, ¿cuál es la fórmula oficial y quién la validó?",
                            "en": "For each of those numbers, what is the official formula and who validated it?",
                            "pt": "Para cada um desses números, qual é a fórmula oficial e quem a validou?"},
    "rq_reporte_formulas_por": {"es": "El mismo KPI calculado de dos maneras es la discusión que se repite en cada reunión hasta que alguien la escribe.",
                                "en": "The same KPI computed two ways is the argument that repeats in every meeting until someone writes it down.",
                                "pt": "O mesmo KPI calculado de duas maneiras é a discussão que se repete em toda reunião até alguém escrevê-la."},
    "rq_reporte_audiencia": {"es": "¿Quién lo va a mirar, con qué frecuencia y en qué dispositivo?",
                             "en": "Who will look at it, how often and on what device?",
                             "pt": "Quem vai olhar, com que frequência e em qual dispositivo?"},
    "rq_reporte_audiencia_por": {"es": "Un tablero para gerencia en el celular no se diseña igual que uno operativo en dos monitores.",
                                 "en": "A management dashboard on a phone is not designed like an operational one on two monitors.",
                                 "pt": "Um painel gerencial no celular não se desenha igual a um operacional em dois monitores."},
    "rq_reporte_cortes": {"es": "¿Por qué dimensiones se necesita abrir cada número?",
                          "en": "By which dimensions does each number need to be broken down?",
                          "pt": "Por quais dimensões cada número precisa ser aberto?"},
    "rq_reporte_cortes_por": {"es": "Cada corte que se pide obliga a tener esa columna desde la fuente: pedirlo tarde es rehacer el pipeline.",
                              "en": "Every breakdown requested requires that column from the source: asking late means redoing the pipeline.",
                              "pt": "Cada corte pedido obriga a ter aquela coluna desde a fonte: pedir tarde é refazer o pipeline."},
    "rq_reporte_hoy": {"es": "¿Cómo se hace hoy ese reporte, quién lo hace y cuánto tiempo le lleva?",
                       "en": "How is that report produced today, who does it and how long does it take?",
                       "pt": "Como esse relatório é feito hoje, quem faz e quanto tempo leva?"},
    "rq_reporte_hoy_por": {"es": "Es la línea de base para medir el ahorro, y muestra los cálculos escondidos que nadie documentó.",
                           "en": "It is the baseline for measuring the saving, and it surfaces the hidden calculations nobody documented.",
                           "pt": "É a linha de base para medir a economia, e revela os cálculos escondidos que ninguém documentou."},

    # ------------------------------------------------------------- 10 · DAX
    "rq_dax_medidas": {"es": "¿Ya existen medidas o cálculos en la herramienta de BI actual que haya que replicar tal cual?",
                       "en": "Do measures or calculations already exist in the current BI tool that must be replicated as they are?",
                       "pt": "Já existem medidas ou cálculos na ferramenta de BI atual que precisem ser replicados igual?"},
    "rq_dax_medidas_por": {"es": "Migrar sin replicar exactamente es garantía de que alguien va a decir «antes daba otra cosa».",
                           "en": "Migrating without replicating exactly guarantees someone will say “it used to give something else”.",
                           "pt": "Migrar sem replicar exatamente garante que alguém vai dizer «antes dava outra coisa»."},
    "rq_dax_comparaciones": {"es": "¿Se comparan períodos: mes anterior, mismo mes del año pasado, acumulado del año?",
                             "en": "Are periods compared: previous month, same month last year, year to date?",
                             "pt": "Comparam-se períodos: mês anterior, mesmo mês do ano passado, acumulado do ano?"},
    "rq_dax_comparaciones_por": {"es": "Define las medidas de inteligencia de tiempo y obliga a tener una tabla de calendario completa.",
                                 "en": "Defines the time-intelligence measures and requires a complete calendar table.",
                                 "pt": "Define as medidas de inteligência de tempo e exige uma tabela de calendário completa."},

    # ------------------------------------------------------------- 11 · Power BI
    "rq_powerbi_herramienta": {"es": "¿Con qué herramienta se visualiza: Power BI, Tableau, otra? ¿Qué licencias hay disponibles?",
                               "en": "Which tool is used for visualisation: Power BI, Tableau, another? What licences are available?",
                               "pt": "Com qual ferramenta se visualiza: Power BI, Tableau, outra? Quais licenças estão disponíveis?"},
    "rq_powerbi_herramienta_por": {"es": "Sin licencias para la audiencia real, el mejor tablero del mundo lo ve una sola persona.",
                                   "en": "Without licences for the real audience, the world's best dashboard is seen by one person.",
                                   "pt": "Sem licenças para a audiência real, o melhor painel do mundo é visto por uma pessoa só."},
    "rq_powerbi_publicacion": {"es": "¿Dónde se publica y quién administra ese espacio de trabajo?",
                               "en": "Where is it published and who administers that workspace?",
                               "pt": "Onde é publicado e quem administra esse espaço de trabalho?"},
    "rq_powerbi_publicacion_por": {"es": "Determina el circuito de publicación y quién puede romper el tablero sin querer.",
                                   "en": "Determines the publishing path and who can break the dashboard by accident.",
                                   "pt": "Determina o circuito de publicação e quem pode quebrar o painel sem querer."},
    "rq_powerbi_refresco": {"es": "¿Cada cuánto tiene que refrescarse el tablero, y a qué hora tiene que estar actualizado?",
                            "en": "How often must the dashboard refresh, and by what time must it be up to date?",
                            "pt": "De quanto em quanto tempo o painel precisa atualizar, e a que hora precisa estar atualizado?"},
    "rq_powerbi_refresco_por": {"es": "Va a la frecuencia esperada del monitoreo de cargas: es contra ese horario que se mide si llegó tarde.",
                                "en": "Feeds the expected frequency in load monitoring: lateness is measured against that time.",
                                "pt": "Alimenta a frequência esperada do monitoramento de cargas: o atraso é medido contra esse horário."},

    # ------------------------------------------------------------- 12 · entrega
    "rq_entrega_frecuencia": {"es": "¿Cada cuánto tiene que correr el proceso completo y a qué hora tiene que estar listo?",
                              "en": "How often must the whole process run, and by what time must it be ready?",
                              "pt": "De quanto em quanto tempo o processo completo precisa rodar, e a que hora precisa estar pronto?"},
    "rq_entrega_frecuencia_por": {"es": "Es la automatización y la tolerancia del monitoreo. «Cuando se pueda» no es una frecuencia.",
                                  "en": "It is the automation and the monitoring tolerance. “Whenever” is not a frequency.",
                                  "pt": "É a automação e a tolerância do monitoramento. «Quando der» não é uma frequência."},
    "rq_entrega_responsable": {"es": "Cuando esto esté productivo, ¿quién lo opera y quién lo mantiene?",
                               "en": "Once this is in production, who operates it and who maintains it?",
                               "pt": "Quando isto estiver em produção, quem opera e quem mantém?"},
    "rq_entrega_responsable_por": {"es": "Un proceso sin dueño operativo funciona hasta el primer error y después queda apagado meses.",
                                   "en": "A process with no operational owner works until the first error and then stays off for months.",
                                   "pt": "Um processo sem dono operacional funciona até o primeiro erro e depois fica desligado por meses."},
    "rq_entrega_falla": {"es": "Si un día falla, ¿cuál es el plan? ¿Se puede publicar tarde, o directamente no se publica?",
                         "en": "If it fails one day, what is the plan? Can it be published late, or not published at all?",
                         "pt": "Se um dia falhar, qual é o plano? Pode publicar atrasado, ou simplesmente não se publica?"},
    "rq_entrega_falla_por": {"es": "Define si las reglas de calidad cortan o sólo avisan, y qué se le dice al que espera el número.",
                             "en": "Decides whether quality rules stop or only warn, and what to tell whoever is waiting for the number.",
                             "pt": "Define se as regras de qualidade cortam ou só avisam, e o que se diz a quem espera o número."},
    "rq_entrega_exito": {"es": "¿Cómo vamos a saber, dentro de tres meses, que esto salió bien?",
                         "en": "How will we know, three months from now, that this went well?",
                         "pt": "Como vamos saber, daqui a três meses, que isto deu certo?"},
    "rq_entrega_exito_por": {"es": "Sin criterio de éxito acordado al principio, el cierre del proyecto es una opinión de quien hable más fuerte.",
                             "en": "With no success criterion agreed up front, closing the project is the opinion of whoever speaks loudest.",
                             "pt": "Sem critério de sucesso acordado no início, o encerramento do projeto é a opinião de quem fala mais alto."},
}
